# Generated by Django 5.2.15 on 2026-06-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=160, verbose_name='nombre comercial')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('public_description', models.TextField(blank=True, verbose_name='descripcion publica')),
                ('public_phone', models.CharField(blank=True, max_length=32, verbose_name='telefono publico')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='email publico')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='localidad')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='provincia')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'ordering': ['commercial_name'],
                'indexes': [models.Index(fields=['is_active'], name='business_active_idx'), models.Index(fields=['slug'], name='business_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professional_admin', 'Administrador profesional')], default='professional_admin', max_length=40, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business', verbose_name='negocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pertenencia profesional',
                'verbose_name_plural': 'pertenencias profesionales',
                'ordering': ['business__commercial_name', 'user__full_name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='membership_business_active_idx'), models.Index(fields=['user', 'is_active'], name='membership_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'user'), name='unique_business_membership')],
            },
        ),
    ]
