# Generated by Django 5.2.15 on 2026-07-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_business_public_booking_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="business",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="última actividad"),
        ),
        migrations.AlterField(
            model_name="business",
            name="public_description",
            field=models.TextField(blank=True, verbose_name="descripción pública"),
        ),
        migrations.AlterField(
            model_name="business",
            name="public_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="correo público"),
        ),
        migrations.AlterField(
            model_name="business",
            name="public_phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="teléfono público"),
        ),
        migrations.AlterField(
            model_name="business",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="businessmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.CreateModel(
            name="BusinessActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("professional", "Profesional"),
                            ("customer", "Cliente"),
                            ("superadmin", "Superadministrador"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="tipo de actor",
                    ),
                ),
                ("actor_label", models.CharField(max_length=160, verbose_name="actor")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("appointments", "Citas"),
                            ("configuration", "Configuración"),
                            ("access", "Accesos"),
                            ("platform", "Plataforma"),
                        ],
                        max_length=24,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("appointment_created", "Cita creada"),
                            ("appointment_cancelled", "Cita cancelada"),
                            ("appointment_completed", "Cita atendida"),
                            ("appointment_no_show", "Ausencia registrada"),
                            ("service_created", "Servicio creado"),
                            ("service_updated", "Servicio actualizado"),
                            ("service_paused", "Servicio pausado"),
                            ("service_reactivated", "Servicio reactivado"),
                            ("availability_created", "Horario creado"),
                            ("availability_updated", "Horario actualizado"),
                            ("availability_paused", "Horario pausado"),
                            ("availability_reactivated", "Horario reactivado"),
                            ("closure_created", "Cierre creado"),
                            ("closure_updated", "Cierre actualizado"),
                            ("closure_paused", "Cierre pausado"),
                            ("closure_reactivated", "Cierre reactivado"),
                            ("work_line_created", "Línea creada"),
                            ("work_line_updated", "Línea actualizada"),
                            ("work_line_paused", "Línea pausada"),
                            ("work_line_reactivated", "Línea reactivada"),
                            ("business_created", "Negocio creado"),
                            ("business_updated", "Negocio actualizado"),
                            ("business_paused", "Negocio pausado"),
                            ("business_reactivated", "Negocio reactivado"),
                            ("public_booking_enabled", "Reserva pública activada"),
                            ("public_booking_disabled", "Reserva pública pausada"),
                            ("membership_created", "Acceso profesional creado"),
                            ("membership_paused", "Acceso profesional pausado"),
                            ("membership_reactivated", "Acceso profesional reactivado"),
                        ],
                        max_length=40,
                        verbose_name="tipo de evento",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("telefono", "Teléfono"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Correo electrónico"),
                            ("mostrador", "Mostrador"),
                            ("web_publica", "Reserva online"),
                            ("panel_profesional", "Panel profesional"),
                            ("plataforma", "Administración de la plataforma"),
                            ("sistema", "Sistema"),
                            ("otro", "Otro"),
                        ],
                        max_length=24,
                        verbose_name="origen",
                    ),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="resumen")),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=40, verbose_name="tipo de entidad"),
                ),
                (
                    "entity_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="identificador de entidad",
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict, verbose_name="cambios")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="fecha y hora")),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_activity_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario actor",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="businesses.business",
                        verbose_name="negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento del negocio",
                "verbose_name_plural": "movimientos del negocio",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["business", "-id"], name="biz_activity_recent_idx"),
                    models.Index(
                        fields=["business", "category", "-id"],
                        name="biz_activity_cat_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("summary", ""), _negated=True),
                        name="business_activity_summary_not_empty",
                    )
                ],
            },
        ),
    ]
