# Generated by Django 5.2.15 on 2026-07-10 18:53

import apps.businesses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='professional_theme',
            field=models.CharField(choices=[('light', 'Modo claro'), ('dark', 'Modo oscuro')], default='light', max_length=12, verbose_name='tema del panel profesional'),
        ),
        migrations.AddField(
            model_name='business',
            name='public_image',
            field=models.ImageField(blank=True, upload_to=apps.businesses.models.business_public_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagen pública personalizada'),
        ),
        migrations.AlterField(
            model_name='businessactivityevent',
            name='event_type',
            field=models.CharField(choices=[('appointment_created', 'Cita creada'), ('appointment_cancelled', 'Cita cancelada'), ('appointment_completed', 'Cita atendida'), ('appointment_no_show', 'Ausencia registrada'), ('service_created', 'Servicio creado'), ('service_updated', 'Servicio actualizado'), ('service_paused', 'Servicio pausado'), ('service_reactivated', 'Servicio reactivado'), ('availability_created', 'Horario creado'), ('availability_updated', 'Horario actualizado'), ('availability_paused', 'Horario pausado'), ('availability_reactivated', 'Horario reactivado'), ('closure_created', 'Cierre creado'), ('closure_updated', 'Cierre actualizado'), ('closure_paused', 'Cierre pausado'), ('closure_reactivated', 'Cierre reactivado'), ('work_line_created', 'Línea creada'), ('work_line_updated', 'Línea actualizada'), ('work_line_paused', 'Línea pausada'), ('work_line_reactivated', 'Línea reactivada'), ('business_created', 'Negocio creado'), ('business_updated', 'Negocio actualizado'), ('business_paused', 'Negocio pausado'), ('business_reactivated', 'Negocio reactivado'), ('public_booking_enabled', 'Reserva pública activada'), ('public_booking_disabled', 'Reserva pública pausada'), ('visual_settings_updated', 'Apariencia actualizada'), ('membership_created', 'Acceso profesional creado'), ('membership_paused', 'Acceso profesional pausado'), ('membership_reactivated', 'Acceso profesional reactivado')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
