# Generated by Django 5.2.16 on 2026-07-11 18:54

import apps.businesses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_public_images(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    BusinessPublicImage = apps.get_model("businesses", "BusinessPublicImage")

    for business in Business.objects.all():
        identity = f"{business.slug} {business.commercial_name}".lower()
        preset = "barberia" if "barber" in identity else "salon"
        Business.objects.filter(pk=business.pk).update(public_image_preset=preset)
        if business.public_image:
            BusinessPublicImage.objects.create(
                business=business,
                image=business.public_image.name,
                label="Imagen personalizada",
                is_selected=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_businessactivityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='public_image_preset',
            field=models.CharField(choices=[('salon', 'Salón luminoso'), ('barberia', 'Barbería contemporánea')], default='salon', max_length=16, verbose_name='imagen pública predeterminada'),
        ),
        migrations.CreateModel(
            name='BusinessPublicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.businesses.models.business_public_gallery_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagen')),
                ('label', models.CharField(max_length=120, verbose_name='nombre visible')),
                ('is_selected', models.BooleanField(default=False, verbose_name='seleccionada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_images', to='businesses.business', verbose_name='negocio')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_business_public_images', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'imagen pública de negocio',
                'verbose_name_plural': 'imágenes públicas de negocio',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='pubimg_business_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('business',), name='unique_selected_public_image_per_business')],
            },
        ),
        migrations.RunPython(migrate_existing_public_images, migrations.RunPython.noop),
    ]
