# Generated by Django 5.2.16 on 2026-07-12 05:36

import apps.businesses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_public_image_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_theme', models.CharField(choices=[('light', 'Modo claro'), ('dark', 'Modo oscuro')], default='light', max_length=12, verbose_name='tema de la administración')),
                ('login_image_preset', models.CharField(choices=[('agendasalon', 'AgendaSalon'), ('salon', 'Salón luminoso'), ('barberia', 'Barbería contemporánea')], default='agendasalon', max_length=16, verbose_name='imagen predeterminada del acceso interno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_platform_settings', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'ajustes de plataforma',
                'verbose_name_plural': 'ajustes de plataforma',
            },
        ),
        migrations.CreateModel(
            name='PlatformLoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.businesses.models.platform_login_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagen')),
                ('label', models.CharField(max_length=120, verbose_name='nombre visible')),
                ('is_selected', models.BooleanField(default=False, verbose_name='seleccionada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_platform_login_images', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
                ('platform_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_images', to='businesses.platformsettings', verbose_name='ajustes de plataforma')),
            ],
            options={
                'verbose_name': 'imagen de acceso de plataforma',
                'verbose_name_plural': 'imágenes de acceso de plataforma',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('platform_settings',), name='unique_selected_platform_login_image')],
            },
        ),
    ]
