# Generated by Django 5.2.16 on 2026-07-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_business_legal_compliance_enabled_and_more'),
        ('legal', '0006_legal_notice_2026_07_3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160, verbose_name='nombre comercial')),
                ('business_type', models.CharField(choices=[('hair_salon', 'Peluquería'), ('barbershop', 'Barbería'), ('beauty_salon', 'Salón de belleza'), ('other', 'Otro')], max_length=24, verbose_name='tipo de negocio')),
                ('city', models.CharField(max_length=120, verbose_name='localidad')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='provincia')),
                ('contact_name', models.CharField(max_length=150, verbose_name='persona de contacto')),
                ('phone', models.CharField(max_length=32, verbose_name='teléfono')),
                ('normalized_phone', models.CharField(db_index=True, max_length=32, verbose_name='teléfono normalizado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('preferred_channel', models.CharField(choices=[('phone', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('email', 'Correo electrónico')], max_length=16, verbose_name='canal preferido')),
                ('need_text', models.CharField(blank=True, max_length=300, verbose_name='necesidad principal')),
                ('privacy_document_version', models.CharField(max_length=24, verbose_name='versión de privacidad')),
                ('privacy_document_hash', models.CharField(max_length=64, verbose_name='huella de privacidad')),
                ('privacy_acknowledged_at', models.DateTimeField(verbose_name='información de privacidad leída')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('reviewing', 'En revisión'), ('contacted', 'Contactada'), ('converted', 'Convertida'), ('dismissed', 'Descartada')], db_index=True, default='new', max_length=16, verbose_name='estado')),
                ('admin_note', models.TextField(blank=True, max_length=1000, verbose_name='nota interna')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='convertida el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibida el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('converted_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signup_requests', to='businesses.business', verbose_name='negocio creado')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_business_signup_requests', to=settings.AUTH_USER_MODEL, verbose_name='gestionada por')),
                ('privacy_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_signup_requests', to='legal.legaldocument', verbose_name='información de privacidad mostrada')),
            ],
            options={
                'verbose_name': 'solicitud de alta de negocio',
                'verbose_name_plural': 'solicitudes de alta de negocio',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='signup_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('converted_at__isnull', False), ('converted_business__isnull', False), ('status', 'converted')), models.Q(models.Q(('status', 'converted'), _negated=True), ('converted_at__isnull', True), ('converted_business__isnull', True)), _connector='OR'), name='signup_conversion_fields_coherent')],
            },
        ),
    ]
