# Generated by Django 5.2.16 on 2026-07-18 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_businesssignuprequest_privacy_legal_context_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo de avisos'),
        ),
        migrations.AddField(
            model_name='business',
            name='notification_email_normalized',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='correo de avisos normalizado'),
        ),
        migrations.AddField(
            model_name='business',
            name='notification_email_verification_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='nonce de verificación del correo de avisos'),
        ),
        migrations.AddField(
            model_name='business',
            name='notification_email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='correo de avisos verificado el'),
        ),
        migrations.AddField(
            model_name='business',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='avisos por correo activos'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_cancellations',
            field=models.BooleanField(default=True, verbose_name='avisar de cancelaciones'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_client_access',
            field=models.BooleanField(default=True, verbose_name='avisar de altas cliente'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_email_failures',
            field=models.BooleanField(default=True, verbose_name='avisar de fallos de correo'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_holiday_reviews',
            field=models.BooleanField(default=True, verbose_name='avisar de revisiones por festivos'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_new_appointments',
            field=models.BooleanField(default=True, verbose_name='avisar de nuevas citas'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo de avisos'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email_normalized',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='correo de avisos normalizado'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email_verification_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='nonce de verificación del correo de avisos'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='correo de avisos verificado el'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='avisos por correo activos'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_continuity',
            field=models.BooleanField(default=True, verbose_name='avisar de continuidad'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_demo_refresh',
            field=models.BooleanField(default=True, verbose_name='avisar de regeneraciones'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_email_failures',
            field=models.BooleanField(default=True, verbose_name='avisar de fallos de correo'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_signup_requests',
            field=models.BooleanField(default=True, verbose_name='avisar de solicitudes de alta'),
        ),
        migrations.AlterField(
            model_name='businessactivityevent',
            name='event_type',
            field=models.CharField(choices=[('appointment_created', 'Cita creada'), ('appointment_cancelled', 'Cita cancelada'), ('appointment_completed', 'Cita atendida'), ('appointment_no_show', 'Ausencia registrada'), ('service_created', 'Servicio creado'), ('service_updated', 'Servicio actualizado'), ('service_paused', 'Servicio pausado'), ('service_reactivated', 'Servicio reactivado'), ('availability_created', 'Horario creado'), ('availability_updated', 'Horario actualizado'), ('availability_paused', 'Horario pausado'), ('availability_reactivated', 'Horario reactivado'), ('closure_created', 'Cierre creado'), ('closure_updated', 'Cierre actualizado'), ('closure_paused', 'Cierre pausado'), ('closure_reactivated', 'Cierre reactivado'), ('work_line_created', 'Línea creada'), ('work_line_updated', 'Línea actualizada'), ('work_line_paused', 'Línea pausada'), ('work_line_reactivated', 'Línea reactivada'), ('business_created', 'Negocio creado'), ('business_updated', 'Negocio actualizado'), ('business_paused', 'Negocio pausado'), ('business_reactivated', 'Negocio reactivado'), ('public_booking_enabled', 'Reserva pública activada'), ('public_booking_disabled', 'Reserva pública pausada'), ('visual_settings_updated', 'Apariencia actualizada'), ('notification_settings_updated', 'Avisos actualizados'), ('membership_created', 'Acceso profesional creado'), ('membership_paused', 'Acceso profesional pausado'), ('membership_reactivated', 'Acceso profesional reactivado'), ('client_invitation_created', 'Invitación de cliente creada'), ('client_invitation_revoked', 'Invitación de cliente revocada'), ('client_access_activated', 'Cuenta de cliente activada'), ('national_holidays_enabled', 'Festivos nacionales aplicados'), ('national_holidays_disabled', 'Festivos nacionales desactivados'), ('legal_documentation_accepted', 'Documentación legal aceptada'), ('data_rights_request_updated', 'Solicitud de derechos actualizada')], max_length=40, verbose_name='tipo de evento'),
        ),
        migrations.CreateModel(
            name='PlatformActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('notification_settings_updated', 'Avisos actualizados'), ('notification_email_verified', 'Correo de avisos verificado'), ('notification_test_queued', 'Prueba de correo'), ('notification_capacity_reached', 'Límite de avisos alcanzado')], max_length=48, verbose_name='tipo de evento')),
                ('summary', models.CharField(max_length=255, verbose_name='resumen')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='cambios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_activity_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario actor')),
                ('actor_label', models.CharField(blank=True, max_length=160, verbose_name='identidad del actor')),
            ],
            options={
                'verbose_name': 'movimiento de plataforma',
                'verbose_name_plural': 'movimientos de plataforma',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='platform_event_recent_idx')],
            },
        ),
    ]
