# Generated by Django 5.2.15 on 2026-06-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nombre completo')),
                ('full_name_normalized', models.CharField(editable=False, max_length=180, verbose_name='nombre normalizado')),
                ('phone', models.CharField(max_length=32, verbose_name='telefono')),
                ('phone_normalized', models.CharField(editable=False, max_length=32, verbose_name='telefono normalizado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('source', models.CharField(choices=[('professional', 'Profesional'), ('imported_demo', 'Demo importada'), ('other', 'Otro')], default='professional', max_length=40, verbose_name='origen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima actividad')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'ficha de cliente',
                'verbose_name_plural': 'fichas de cliente',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessClientAuthorizedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nombre completo')),
                ('phone', models.CharField(max_length=32, verbose_name='telefono')),
                ('phone_normalized', models.CharField(editable=False, max_length=32, verbose_name='telefono normalizado')),
                ('relationship_label', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('hija', 'Hija'), ('familiar', 'Familiar'), ('cuidador', 'Cuidador'), ('pareja', 'Pareja'), ('otro', 'Otro')], default='otro', max_length=40, verbose_name='relacion')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='contacto principal')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_authorized_contacts', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_contacts', to='customers.businessclient', verbose_name='ficha de cliente')),
            ],
            options={
                'verbose_name': 'contacto autorizado',
                'verbose_name_plural': 'contactos autorizados',
                'ordering': ['business_client__full_name', '-is_primary_contact', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['business', 'phone_normalized'], name='client_business_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['business', 'full_name_normalized'], name='client_business_name_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['business', 'is_active'], name='client_business_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('business', 'phone_normalized', 'full_name_normalized'), name='unique_active_business_client_identity'),
        ),
        migrations.AddIndex(
            model_name='businessclientauthorizedcontact',
            index=models.Index(fields=['business', 'phone_normalized'], name='contact_business_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclientauthorizedcontact',
            index=models.Index(fields=['business_client', 'is_active'], name='contact_client_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessclientauthorizedcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary_contact', True)), fields=('business_client',), name='unique_primary_active_contact_per_client'),
        ),
    ]
