# Generated by Django 5.2.15 on 2026-07-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='telefono')),
                ('phone_normalized', models.CharField(editable=False, max_length=32, verbose_name='telefono normalizado')),
                ('password_hash', models.CharField(max_length=128, verbose_name='hash de contrasena')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='customers.businessclient', verbose_name='ficha de cliente')),
            ],
            options={
                'verbose_name': 'acceso de cliente',
                'verbose_name_plural': 'accesos de cliente',
                'ordering': ['business__commercial_name', 'business_client__full_name'],
                'indexes': [models.Index(fields=['business', 'phone_normalized'], name='client_access_phone_idx'), models.Index(fields=['business', 'is_active'], name='client_access_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'phone_normalized'), name='unique_business_client_access_phone')],
            },
        ),
    ]
