# Generated by Django 5.2.15 on 2026-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_businessclientaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessclient",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="última actividad"),
        ),
        migrations.AlterField(
            model_name="businessclient",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="businessclient",
            name="phone_normalized",
            field=models.CharField(
                editable=False,
                max_length=32,
                verbose_name="teléfono normalizado",
            ),
        ),
        migrations.AlterField(
            model_name="businessclient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="businessclientaccess",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="último acceso"),
        ),
        migrations.AlterField(
            model_name="businessclientaccess",
            name="password_hash",
            field=models.CharField(max_length=128, verbose_name="hash de contraseña"),
        ),
        migrations.AlterField(
            model_name="businessclientaccess",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="businessclientaccess",
            name="phone_normalized",
            field=models.CharField(
                editable=False,
                max_length=32,
                verbose_name="teléfono normalizado",
            ),
        ),
        migrations.AlterField(
            model_name="businessclientaccess",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="businessclientauthorizedcontact",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="businessclientauthorizedcontact",
            name="phone_normalized",
            field=models.CharField(
                editable=False,
                max_length=32,
                verbose_name="teléfono normalizado",
            ),
        ),
        migrations.AlterField(
            model_name="businessclientauthorizedcontact",
            name="relationship_label",
            field=models.CharField(
                choices=[
                    ("madre", "Madre"),
                    ("padre", "Padre"),
                    ("hija", "Hija"),
                    ("familiar", "Familiar"),
                    ("cuidador", "Cuidador"),
                    ("pareja", "Pareja"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=40,
                verbose_name="relación",
            ),
        ),
        migrations.AlterField(
            model_name="businessclientauthorizedcontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
    ]
