# Generated by Django 5.2.15 on 2026-07-11 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_businessactivityevent_event_type'),
        ('customers', '0003_alter_businessclient_last_activity_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientAccessInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True, verbose_name='resumen del token')),
                ('expires_at', models.DateTimeField(verbose_name='caduca el')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usada el')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_invitations', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_invitations', to='customers.businessclient', verbose_name='ficha de cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_access_invitations', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'invitación de acceso de cliente',
                'verbose_name_plural': 'invitaciones de acceso de cliente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_client', 'expires_at'], name='client_invite_active_idx')],
            },
        ),
    ]
