# Generated by Django 5.2.16 on 2026-07-12 04:08

import django.db.models.deletion
from django.db import migrations, models


def create_self_booking_grants(apps, schema_editor):
    BusinessClientAccess = apps.get_model("customers", "BusinessClientAccess")
    BusinessClientAccessGrant = apps.get_model("customers", "BusinessClientAccessGrant")
    grants = [
        BusinessClientAccessGrant(
            business_id=access.business_id,
            access_id=access.id,
            business_client_id=access.business_client_id,
            relationship_label="titular",
            is_active=True,
        )
        for access in BusinessClientAccess.objects.all().iterator()
    ]
    BusinessClientAccessGrant.objects.bulk_create(grants, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_public_image_gallery'),
        ('customers', '0004_businessclientaccessinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_label', models.CharField(choices=[('titular', 'Es su propia ficha'), ('madre', 'Madre'), ('padre', 'Padre'), ('hija', 'Hija'), ('familiar', 'Familiar'), ('cuidador', 'Cuidador'), ('pareja', 'Pareja'), ('otro', 'Otra relación')], default='otro', max_length=40, verbose_name='relación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_grants', to='customers.businessclientaccess', verbose_name='cuenta online')),
                ('authorized_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_booking_grants', to='customers.businessclientauthorizedcontact', verbose_name='persona autorizada')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_grants', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_booking_grants', to='customers.businessclient', verbose_name='ficha para la que puede reservar')),
            ],
            options={
                'verbose_name': 'permiso de reserva online',
                'verbose_name_plural': 'permisos de reserva online',
                'ordering': ['business_client__full_name', 'access__business_client__full_name'],
                'indexes': [models.Index(fields=['access', 'is_active'], name='access_grant_active_idx'), models.Index(fields=['business_client', 'is_active'], name='client_grant_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('access', 'business_client'), name='unique_access_booking_grant_per_client')],
            },
        ),
        migrations.RunPython(create_self_booking_grants, migrations.RunPython.noop),
    ]
