# Generated by Django 5.2.16 on 2026-07-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_public_image_gallery'),
        ('customers', '0005_businessclientaccessgrant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessclient',
            name='unique_active_business_client_identity',
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='phone_normalized',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='teléfono normalizado'),
        ),
        migrations.AddConstraint(
            model_name='businessclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('phone_normalized', ''), _negated=True)), fields=('business', 'phone_normalized', 'full_name_normalized'), name='unique_active_business_client_identity'),
        ),
    ]
