# Generated by Django 5.2.16 on 2026-07-12 04:50

import django.db.models.deletion
from django.db import migrations, models
import unicodedata


def normalize_text(value):
    decomposed = unicodedata.normalize("NFKD", value or "")
    without_marks = "".join(character for character in decomposed if not unicodedata.combining(character))
    return " ".join(without_marks.casefold().split())


def link_existing_authorized_contacts(apps, schema_editor):
    BusinessClient = apps.get_model("customers", "BusinessClient")
    AuthorizedContact = apps.get_model("customers", "BusinessClientAuthorizedContact")
    for contact in AuthorizedContact.objects.filter(linked_business_client__isnull=True).iterator():
        linked_client = (
            BusinessClient.objects.filter(
                business_id=contact.business_id,
                is_active=True,
                full_name_normalized=normalize_text(contact.full_name),
                phone_normalized=contact.phone_normalized,
            )
            .order_by("pk")
            .first()
        )
        if linked_client is not None and linked_client.id != contact.business_client_id:
            contact.linked_business_client_id = linked_client.id
            contact.save(update_fields=["linked_business_client"])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_public_image_gallery'),
        ('customers', '0006_remove_businessclient_unique_active_business_client_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclientauthorizedcontact',
            name='linked_business_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizations_as_contact', to='customers.businessclient', verbose_name='ficha de la persona autorizada'),
        ),
        migrations.RunPython(link_existing_authorized_contacts, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='businessclientauthorizedcontact',
            index=models.Index(fields=['linked_business_client', 'is_active'], name='contact_linked_client_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessclientauthorizedcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_business_client__isnull', False)), fields=('business_client', 'linked_business_client'), name='unique_linked_authorized_client_per_file'),
        ),
    ]
