# Generated by Django 5.2.16 on 2026-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_businessclientauthorizedcontact_linked_business_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclientaccessgrant',
            name='relationship_label',
            field=models.CharField(choices=[('titular', 'Es su propia ficha'), ('madre', 'Madre'), ('padre', 'Padre'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('familiar', 'Familiar'), ('cuidador', 'Cuidador'), ('pareja', 'Pareja'), ('otro', 'Otra relación')], default='otro', max_length=40, verbose_name='relación'),
        ),
        migrations.AlterField(
            model_name='businessclientauthorizedcontact',
            name='relationship_label',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('familiar', 'Familiar'), ('cuidador', 'Cuidador'), ('pareja', 'Pareja'), ('otro', 'Otro')], default='otro', max_length=40, verbose_name='relación'),
        ),
    ]
