# Generated by Django 5.2.16 on 2026-07-14 15:50

from django.db import migrations, models


def copy_known_client_emails(apps, schema_editor):
    Access = apps.get_model("customers", "BusinessClientAccess")
    for access in Access.objects.select_related("business_client").all().iterator():
        email = (access.business_client.email or "").strip()
        if email:
            access.email = email
            access.email_normalized = email.lower()
            access.save(update_fields=["email", "email_normalized"])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_businesssignuprequest'),
        ('customers', '0008_alter_businessclientaccessgrant_relationship_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclientaccess',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='businessclientaccess',
            name='email_normalized',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True, verbose_name='correo normalizado'),
        ),
        migrations.AddField(
            model_name='businessclientaccess',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='correo verificado el'),
        ),
        migrations.RunPython(copy_known_client_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='businessclientaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('email_normalized__isnull', False)), fields=('business', 'email_normalized'), name='unique_business_client_access_email'),
        ),
    ]
