# Generated by Django 5.2.15 on 2026-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="normalized_phone",
            field=models.CharField(
                help_text="Teléfono en formato E.164 usado para iniciar sesión.",
                max_length=32,
                unique=True,
                verbose_name="teléfono normalizado",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="teléfono"),
        ),
    ]
