# Generated by Django 5.2.16 on 2026-07-14 15:50

from django.db import migrations, models


def prepare_existing_account_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all().iterator():
        email = (user.email or "").strip()
        if email:
            user.email = email
            user.email_normalized = email.lower()
        user.email_verified_at = None
        user.email_verification_required = user.is_active
        user.save(
            update_fields=[
                "email",
                "email_normalized",
                "email_verified_at",
                "email_verification_required",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_normalized',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True, unique=True, verbose_name='email normalizado'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_required',
            field=models.BooleanField(default=False, help_text='Impide usar la operativa hasta verificar un correo personal.', verbose_name='verificacion de email obligatoria'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email verificado el'),
        ),
        migrations.RunPython(prepare_existing_account_emails, migrations.RunPython.noop),
    ]
