# Generated by Django 5.2.16 on 2026-07-13 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0010_business_legal_compliance_enabled_and_more'),
        ('customers', '0008_alter_businessclientaccessgrant_relationship_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180, verbose_name='nombre o razón social')),
                ('tax_identifier', models.CharField(max_length=40, verbose_name='identificación fiscal')),
                ('registered_address', models.CharField(max_length=255, verbose_name='domicilio')),
                ('privacy_email', models.EmailField(max_length=254, verbose_name='correo para privacidad')),
                ('rights_contact_name', models.CharField(blank=True, max_length=160, verbose_name='persona o área de contacto')),
                ('retention_criteria', models.TextField(verbose_name='criterio de conservación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'perfil legal de negocio',
                'verbose_name_plural': 'perfiles legales de negocio',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('legal_notice', 'Aviso legal'), ('platform_privacy', 'Privacidad de la plataforma'), ('terms', 'Condiciones del servicio'), ('data_processing', 'Encargo de tratamiento'), ('customer_privacy', 'Privacidad de clientes'), ('cookies', 'Política de cookies')], max_length=32, verbose_name='tipo')),
                ('slug', models.SlugField(max_length=80, verbose_name='identificador público')),
                ('version', models.CharField(max_length=24, verbose_name='versión')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('lead', models.TextField(verbose_name='introducción')),
                ('sections', models.JSONField(default=list, verbose_name='secciones')),
                ('content_hash', models.CharField(editable=False, max_length=64, verbose_name='huella SHA-256')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='vigente')),
            ],
            options={
                'verbose_name': 'documento legal',
                'verbose_name_plural': 'documentos legales',
                'ordering': ['kind', '-published_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='unique_legal_document_kind_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kind',), name='unique_active_legal_document_kind')],
            },
        ),
        migrations.CreateModel(
            name='DataRightsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Acceso'), ('rectification', 'Rectificación'), ('erasure', 'Supresión'), ('restriction', 'Limitación'), ('portability', 'Portabilidad'), ('objection', 'Oposición')], max_length=20, verbose_name='derecho')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('in_progress', 'En revisión'), ('resolved', 'Resuelta'), ('dismissed', 'No procede')], default='received', max_length=20, verbose_name='estado')),
                ('resolution_note', models.TextField(blank=True, verbose_name='nota de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibida el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_rights_requests', to='businesses.business', verbose_name='negocio')),
                ('client_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_rights_requests', to='customers.businessclientaccess', verbose_name='cuenta cliente')),
            ],
            options={
                'verbose_name': 'solicitud de derechos',
                'verbose_name_plural': 'solicitudes de derechos',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='rights_request_business_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledged', 'Información recibida'), ('accepted', 'Documento aceptado')], max_length=20, verbose_name='acción')),
                ('context', models.CharField(choices=[('professional_onboarding', 'Alta legal del negocio'), ('client_registration', 'Registro de cliente'), ('client_invitation', 'Activación por invitación'), ('booking_confirmation', 'Confirmación de cita')], max_length=32, verbose_name='contexto')),
                ('document_hash_snapshot', models.CharField(max_length=64, verbose_name='huella aceptada')),
                ('legal_context_snapshot', models.JSONField(default=dict, verbose_name='contexto legal mostrado')),
                ('authority_declared', models.BooleanField(default=False, verbose_name='autoridad declarada')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='profesional')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to='businesses.business', verbose_name='negocio')),
                ('client_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to='customers.businessclientaccess', verbose_name='cuenta cliente')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'aceptación legal',
                'verbose_name_plural': 'aceptaciones legales',
                'ordering': ['-accepted_at', '-pk'],
                'indexes': [models.Index(fields=['business', 'context', '-accepted_at'], name='legal_acceptance_business_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_user__isnull', False), ('client_access__isnull', True)), models.Q(('actor_user__isnull', True), ('client_access__isnull', False)), _connector='OR'), name='legal_acceptance_exactly_one_actor'), models.UniqueConstraint(condition=models.Q(('actor_user__isnull', False)), fields=('document', 'business', 'actor_user', 'context'), name='unique_user_legal_acceptance_context'), models.UniqueConstraint(condition=models.Q(('client_access__isnull', False)), fields=('document', 'business', 'client_access', 'context'), name='unique_client_legal_acceptance_context')],
            },
        ),
    ]
