# Generated by Django 5.2.16 on 2026-07-13 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_business_legal_compliance_enabled_and_more'),
        ('customers', '0008_alter_businessclientaccessgrant_relationship_label_and_more'),
        ('legal', '0002_seed_legal_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrivacyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('acknowledged', 'Información leída por la persona cliente'), ('information_provided', 'Información facilitada por el negocio')], max_length=24, verbose_name='tipo de constancia')),
                ('channel', models.CharField(choices=[('online_registration', 'Registro online'), ('client_invitation', 'Invitación online'), ('booking', 'Confirmación de reserva'), ('phone', 'Teléfono'), ('in_person', 'En el establecimiento'), ('email', 'Correo electrónico'), ('other', 'Otro canal')], max_length=24, verbose_name='canal')),
                ('document_hash_snapshot', models.CharField(max_length=64, verbose_name='huella mostrada')),
                ('legal_context_snapshot', models.JSONField(default=dict, verbose_name='contexto legal mostrado')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora del hecho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_privacy_evidence', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_evidence', to='customers.businessclient', verbose_name='cliente')),
                ('client_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privacy_evidence', to='customers.businessclientaccess', verbose_name='cuenta cliente')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_privacy_evidence', to='legal.legaldocument', verbose_name='documento')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_customer_privacy_evidence', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'constancia de privacidad de cliente',
                'verbose_name_plural': 'constancias de privacidad de clientes',
                'ordering': ['-occurred_at', '-pk'],
                'indexes': [models.Index(fields=['business_client', 'document', '-occurred_at'], name='customer_privacy_client_idx'), models.Index(fields=['business', 'document', '-occurred_at'], name='customer_privacy_business_idx')],
            },
        ),
    ]
