# Generated by Django 5.2.16 on 2026-07-17 06:10

import hashlib

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_legal_evidence_events(apps, schema_editor):
    LegalAcceptance = apps.get_model("legal", "LegalAcceptance")
    LegalAcceptanceEvent = apps.get_model("legal", "LegalAcceptanceEvent")
    CustomerPrivacyEvidence = apps.get_model("legal", "CustomerPrivacyEvidence")
    CustomerPrivacyEvidenceEvent = apps.get_model(
        "legal",
        "CustomerPrivacyEvidenceEvent",
    )
    events = []
    for acceptance in LegalAcceptance.objects.all().iterator(chunk_size=500):
        events.append(
            LegalAcceptanceEvent(
                document_id=acceptance.document_id,
                business_id=acceptance.business_id,
                actor_user_id=acceptance.actor_user_id,
                client_access_id=acceptance.client_access_id,
                action=acceptance.action,
                context=acceptance.context,
                document_hash_snapshot=acceptance.document_hash_snapshot,
                legal_context_snapshot=acceptance.legal_context_snapshot,
                authority_declared=acceptance.authority_declared,
                accepted_at=acceptance.accepted_at,
                recorded_at=acceptance.accepted_at,
                action_fingerprint=hashlib.sha256(
                    f"legacy:legal-acceptance:{acceptance.pk}".encode()
                ).hexdigest(),
            )
        )
        if len(events) == 500:
            LegalAcceptanceEvent.objects.bulk_create(
                events,
                batch_size=500,
            )
            events = []
    if events:
        LegalAcceptanceEvent.objects.bulk_create(
            events,
            batch_size=500,
        )

    events = []
    for evidence in CustomerPrivacyEvidence.objects.all().iterator(chunk_size=500):
        events.append(
            CustomerPrivacyEvidenceEvent(
                document_id=evidence.document_id,
                business_id=evidence.business_id,
                business_client_id=evidence.business_client_id,
                client_access_id=evidence.client_access_id,
                recorded_by_id=evidence.recorded_by_id,
                event_type=evidence.event_type,
                channel=evidence.channel,
                informed_party_type=evidence.informed_party_type,
                informed_party_name_snapshot=evidence.informed_party_name_snapshot,
                document_hash_snapshot=evidence.document_hash_snapshot,
                legal_context_snapshot=evidence.legal_context_snapshot,
                occurred_at=evidence.occurred_at,
                recorded_at=evidence.created_at,
                action_fingerprint=hashlib.sha256(
                    f"legacy:customer-privacy-evidence:{evidence.pk}".encode()
                ).hexdigest(),
            )
        )
        if len(events) == 500:
            CustomerPrivacyEvidenceEvent.objects.bulk_create(
                events,
                batch_size=500,
            )
            events = []
    if events:
        CustomerPrivacyEvidenceEvent.objects.bulk_create(
            events,
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0012_businesssignuprequest_privacy_legal_context_snapshot"),
        ("customers", "0014_sync_business_client_email_from_access"),
        ("legal", "0006_legal_notice_2026_07_3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAcceptanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Información recibida"),
                            ("accepted", "Documento aceptado"),
                        ],
                        max_length=20,
                        verbose_name="acción",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("professional_onboarding", "Alta legal del negocio"),
                            ("client_registration", "Registro de cliente"),
                            ("client_invitation", "Activación por invitación"),
                            ("booking_confirmation", "Confirmación de cita"),
                        ],
                        max_length=32,
                        verbose_name="contexto",
                    ),
                ),
                (
                    "document_hash_snapshot",
                    models.CharField(max_length=64, verbose_name="huella aceptada"),
                ),
                (
                    "legal_context_snapshot",
                    models.JSONField(
                        default=dict,
                        verbose_name="contexto legal mostrado",
                    ),
                ),
                (
                    "authority_declared",
                    models.BooleanField(
                        default=False,
                        verbose_name="declaró tener autorización",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha y hora",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="registrado el",
                    ),
                ),
                (
                    "action_fingerprint",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="identificador único de la acción",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptance_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profesional",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptance_events",
                        to="businesses.business",
                        verbose_name="negocio",
                    ),
                ),
                (
                    "client_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptance_events",
                        to="customers.businessclientaccess",
                        verbose_name="cuenta cliente",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance_events",
                        to="legal.legaldocument",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de aceptación legal",
                "verbose_name_plural": "eventos de aceptación legal",
                "ordering": ["-accepted_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "context", "-accepted_at"],
                        name="legal_event_business_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor_user__isnull", False),
                                ("client_access__isnull", True),
                            ),
                            models.Q(
                                ("actor_user__isnull", True),
                                ("client_access__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="legal_event_exactly_one_actor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerPrivacyEvidenceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Información leída por la persona cliente"),
                            ("information_provided", "Información facilitada por el negocio"),
                        ],
                        max_length=24,
                        verbose_name="tipo de constancia",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("online_registration", "Registro online"),
                            ("client_invitation", "Invitación online"),
                            ("booking", "Confirmación de reserva"),
                            ("phone", "Teléfono"),
                            ("whatsapp", "WhatsApp"),
                            ("in_person", "En el establecimiento"),
                            ("email", "Correo electrónico"),
                            ("other", "Otro canal"),
                        ],
                        max_length=24,
                        verbose_name="canal",
                    ),
                ),
                (
                    "informed_party_type",
                    models.CharField(
                        choices=[
                            ("client", "Cliente"),
                            ("authorized_person", "Persona autorizada"),
                        ],
                        default="client",
                        max_length=24,
                        verbose_name="persona informada",
                    ),
                ),
                (
                    "informed_party_name_snapshot",
                    models.CharField(
                        max_length=160,
                        verbose_name="nombre de la persona informada",
                    ),
                ),
                (
                    "document_hash_snapshot",
                    models.CharField(max_length=64, verbose_name="huella mostrada"),
                ),
                (
                    "legal_context_snapshot",
                    models.JSONField(
                        default=dict,
                        verbose_name="contexto legal mostrado",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha y hora del hecho",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="registrado el",
                    ),
                ),
                (
                    "action_fingerprint",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="identificador único de la acción",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_privacy_evidence_events",
                        to="businesses.business",
                        verbose_name="negocio",
                    ),
                ),
                (
                    "business_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privacy_evidence_events",
                        to="customers.businessclient",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "client_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privacy_evidence_events",
                        to="customers.businessclientaccess",
                        verbose_name="cuenta cliente",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_privacy_evidence_events",
                        to="legal.legaldocument",
                        verbose_name="documento",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_customer_privacy_evidence_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de privacidad de cliente",
                "verbose_name_plural": "eventos de privacidad de clientes",
                "ordering": ["-occurred_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["business_client", "document", "-occurred_at"],
                        name="privacy_event_client_idx",
                    ),
                    models.Index(
                        fields=["business", "document", "-occurred_at"],
                        name="privacy_event_business_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_legal_evidence_events,
        ),
    ]
