# Generated by Django 5.2.15 on 2026-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, verbose_name='ámbito')),
                ('key_digest', models.CharField(max_length=64, verbose_name='resumen del identificador')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='intentos')),
                ('window_started_at', models.DateTimeField(verbose_name='inicio de ventana')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado hasta')),
                ('last_attempt_at', models.DateTimeField(verbose_name='último intento')),
            ],
            options={
                'verbose_name': 'límite de seguridad',
                'verbose_name_plural': 'límites de seguridad',
                'indexes': [models.Index(fields=['scope', 'blocked_until'], name='security_throttle_block_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_digest'), name='unique_security_throttle_scope_key')],
            },
        ),
    ]
