# Generated by Django 5.2.15 on 2026-07-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRefreshReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="identificador de ejecución",
                    ),
                ),
                ("base_date", models.DateField(verbose_name="fecha base")),
                (
                    "fingerprint",
                    models.CharField(max_length=64, verbose_name="huella del escenario"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="finalización",
                    ),
                ),
            ],
            options={
                "verbose_name": "recibo de regeneración demo",
                "verbose_name_plural": "recibos de regeneración demo",
                "ordering": ("-completed_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("run_id__regex", "^[A-Za-z0-9][A-Za-z0-9_.:-]{15,127}$")
                        ),
                        name="demo_refresh_receipt_run_id_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="demo_refresh_receipt_fingerprint_valid",
                    ),
                ],
            },
        ),
    ]
