# Generated by Django 5.2.16 on 2026-07-18 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demorefreshreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('base_date', models.DateField(verbose_name='fecha base')),
                ('status', models.CharField(choices=[('pending', 'Solicitada'), ('processing', 'En curso'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=16, verbose_name='estado')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='solicitud')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('failure_code', models.CharField(blank=True, help_text='Código acotado sin errores originales, rutas, secretos ni datos personales.', max_length=48, verbose_name='código de fallo')),
                ('origin_digest', models.CharField(max_length=64, verbose_name='resumen criptográfico de origen')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_requests', to='core.demorefreshreceipt', verbose_name='recibo técnico')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_refresh_requests', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'solicitud de regeneración demo',
                'verbose_name_plural': 'solicitudes de regeneración demo',
                'ordering': ('-requested_at', '-id'),
                'indexes': [models.Index(fields=['status', 'requested_at'], name='demo_refresh_req_status_idx')],
                'constraints': [models.UniqueConstraint(models.Value(1), condition=models.Q(('status__in', ('pending', 'processing'))), name='unique_active_demo_refresh_request'), models.CheckConstraint(condition=models.Q(('origin_digest__regex', '^[0-9a-f]{64}$')), name='demo_refresh_request_origin_digest_valid'), models.CheckConstraint(condition=models.Q(('failure_code', ''), ('failure_code__regex', '^[a-z0-9_]{1,48}$'), _connector='OR'), name='demo_refresh_request_failure_code_valid'), models.CheckConstraint(condition=models.Q(models.Q(('failure_code', ''), ('finished_at__isnull', True), ('receipt__isnull', True), ('started_at__isnull', True), ('status', 'pending')), models.Q(('failure_code', ''), ('finished_at__isnull', True), ('receipt__isnull', True), ('started_at__isnull', False), ('status', 'processing')), models.Q(('failure_code', ''), ('finished_at__isnull', False), ('receipt__isnull', False), ('started_at__isnull', False), ('status', 'completed')), models.Q(('finished_at__isnull', False), ('started_at__isnull', False), ('status', 'failed'), models.Q(('failure_code', ''), _negated=True)), models.Q(('failure_code', ''), ('finished_at__isnull', False), ('receipt__isnull', True), ('status', 'cancelled')), _connector='OR'), name='demo_refresh_request_state_valid')],
            },
        ),
    ]
