# Generated by Django 5.2.16 on 2026-07-13 17:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En curso'), ('succeeded', 'Correcta'), ('failed', 'Fallida')], default='running', max_length=16, verbose_name='estado')),
                ('destination', models.CharField(choices=[('local', 'Almacenamiento local'), ('external_encrypted', 'Destino externo cifrado')], default='local', max_length=24, verbose_name='destino')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('database_included', models.BooleanField(default=False, verbose_name='base de datos incluida')),
                ('media_included', models.BooleanField(default=False, verbose_name='archivos incluidos')),
                ('integrity_verified', models.BooleanField(default=False, verbose_name='integridad verificada')),
                ('authenticity_verified', models.BooleanField(default=False, verbose_name='autenticidad verificada')),
                ('total_size_bytes', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tamaño total en bytes')),
                ('failure_code', models.CharField(blank=True, help_text='Código técnico acotado; nunca contiene el error original ni secretos.', max_length=48, verbose_name='código de fallo')),
            ],
            options={
                'verbose_name': 'ejecución de copia',
                'verbose_name_plural': 'ejecuciones de copia',
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['-started_at'], name='backup_exec_recent_idx'), models.Index(fields=['status', '-started_at'], name='backup_exec_status_idx')],
            },
        ),
    ]
