# Generated by Django 5.2.15 on 2026-06-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('scope', models.CharField(choices=[('nacional', 'Nacional'), ('autonomico', 'Autonomico'), ('local', 'Local')], max_length=40, verbose_name='ambito')),
                ('year', models.PositiveSmallIntegerField(verbose_name='anio')),
                ('source_name', models.CharField(max_length=160, verbose_name='fuente')),
                ('source_url', models.URLField(blank=True, verbose_name='url fuente')),
                ('official_reference', models.CharField(blank=True, max_length=180, verbose_name='referencia oficial')),
                ('loaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'verbose_name': 'festivo oficial',
                'verbose_name_plural': 'festivos oficiales',
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['year', 'scope'], name='holiday_year_scope_idx'), models.Index(fields=['date'], name='holiday_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'name', 'scope'), name='unique_official_holiday')],
            },
        ),
        migrations.CreateModel(
            name='HolidaySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='anio')),
                ('source_name', models.CharField(max_length=160, verbose_name='fuente')),
                ('source_url', models.URLField(blank=True, verbose_name='url fuente')),
                ('status', models.CharField(choices=[('success', 'Correcta'), ('failed', 'Fallida'), ('partial', 'Parcial')], max_length=20, verbose_name='estado')),
                ('started_at', models.DateTimeField(verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('items_loaded', models.PositiveIntegerField(default=0, verbose_name='elementos cargados')),
                ('error_detail', models.TextField(blank=True, verbose_name='detalle de error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_sync_runs', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'carga de festivos',
                'verbose_name_plural': 'cargas de festivos',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['year', 'status'], name='holiday_run_year_status_idx')],
            },
        ),
    ]
