# Generated by Django 5.2.15 on 2026-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holidays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialholiday",
            name="scope",
            field=models.CharField(
                choices=[
                    ("nacional", "Nacional"),
                    ("autonomico", "Autonómico"),
                    ("local", "Local"),
                ],
                max_length=40,
                verbose_name="ámbito",
            ),
        ),
        migrations.AlterField(
            model_name="officialholiday",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="año"),
        ),
        migrations.AlterField(
            model_name="holidaysyncrun",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="año"),
        ),
    ]
