# Generated by Django 5.2.16 on 2026-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holidays_labels'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='officialholiday',
            name='unique_official_holiday',
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='affected_appointments',
            field=models.PositiveIntegerField(default=0, verbose_name='citas afectadas'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='affected_businesses',
            field=models.PositiveIntegerField(default=0, verbose_name='negocios afectados'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='items_created',
            field=models.PositiveIntegerField(default=0, verbose_name='elementos creados'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='items_removed',
            field=models.PositiveIntegerField(default=0, verbose_name='elementos retirados'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='items_skipped',
            field=models.PositiveIntegerField(default=0, verbose_name='elementos conservados'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='items_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='elementos actualizados'),
        ),
        migrations.AddField(
            model_name='holidaysyncrun',
            name='official_reference',
            field=models.CharField(blank=True, max_length=180, verbose_name='referencia oficial'),
        ),
        migrations.AddField(
            model_name='officialholiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AddConstraint(
            model_name='officialholiday',
            constraint=models.UniqueConstraint(fields=('date', 'scope'), name='unique_official_holiday'),
        ),
    ]
