# Generated by Django 5.2.15 on 2026-06-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('total_duration_minutes', models.PositiveIntegerField(verbose_name='duracion total')),
                ('duration_adjustment_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo de ajuste de duracion')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20, verbose_name='estado')),
                ('manual_channel', models.CharField(choices=[('telefono', 'Telefono'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('mostrador', 'Mostrador'), ('otro', 'Otro')], default='telefono', max_length=20, verbose_name='canal manual')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelacion')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo de cancelacion')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('service_summary_snapshot', models.TextField(blank=True, verbose_name='resumen snapshot de servicios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.businessclient', verbose_name='ficha de cliente')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='completado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duracion en minutos')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='precio orientativo')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['business__commercial_name', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('service_name_snapshot', models.CharField(max_length=140, verbose_name='nombre snapshot')),
                ('duration_minutes_snapshot', models.PositiveIntegerField(verbose_name='duracion snapshot')),
                ('price_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='precio snapshot')),
                ('color_hex_snapshot', models.CharField(blank=True, max_length=7, verbose_name='color snapshot')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='booking.appointment', verbose_name='cita')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_services', to='booking.service', verbose_name='servicio original')),
            ],
            options={
                'verbose_name': 'servicio de cita',
                'verbose_name_plural': 'servicios de cita',
                'ordering': ['appointment', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(verbose_name='numero de linea')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_lines', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'linea de trabajo',
                'verbose_name_plural': 'lineas de trabajo',
                'ordering': ['business__commercial_name', 'display_order', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='fecha desde')),
                ('date_to', models.DateField(verbose_name='fecha hasta')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora fin')),
                ('closure_type', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('festivo_local', 'Festivo local'), ('festivo_autonomico_manual', 'Festivo autonomico manual'), ('bloqueo_puntual', 'Bloqueo puntual'), ('cierre_negocio', 'Cierre de negocio'), ('otro', 'Otro')], default='otro', max_length=40, verbose_name='tipo')),
                ('internal_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo interno')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='businesses.business', verbose_name='negocio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_closures', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('work_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures', to='booking.workline', verbose_name='linea de trabajo')),
            ],
            options={
                'verbose_name': 'cierre o bloqueo',
                'verbose_name_plural': 'cierres y bloqueos',
                'ordering': ['business__commercial_name', '-date_from', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='work_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.workline', verbose_name='linea de trabajo'),
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='dia de semana')),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'regla de disponibilidad',
                'verbose_name_plural': 'reglas de disponibilidad',
                'ordering': ['business__commercial_name', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['business', 'weekday', 'is_active'], name='availability_business_day_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='BusinessCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='intervalo de hueco')),
                ('apply_national_holidays', models.BooleanField(default=True, verbose_name='aplicar festivos nacionales')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='businesses.business', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'configuracion de calendario',
                'verbose_name_plural': 'configuraciones de calendario',
                'constraints': [models.CheckConstraint(condition=models.Q(('slot_interval_minutes__gt', 0)), name='calendar_slot_interval_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['business', 'is_active'], name='service_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['business', 'display_order'], name='service_business_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.UniqueConstraint(fields=('appointment', 'display_order'), name='unique_appointment_service_order'),
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes_snapshot__gt', 0)), name='appointment_service_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='workline',
            index=models.Index(fields=['business', 'is_active'], name='workline_business_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.UniqueConstraint(fields=('business', 'line_number'), name='unique_business_work_line_number'),
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gte', 1), ('line_number__lte', 3)), name='work_line_number_between_1_and_3'),
        ),
        migrations.AddIndex(
            model_name='businessclosure',
            index=models.Index(fields=['business', 'is_active'], name='closure_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclosure',
            index=models.Index(fields=['business', 'date_from', 'date_to'], name='closure_business_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessclosure',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__lte', models.F('date_to'))), name='closure_date_from_before_date_to'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'starts_at'], name='appointment_business_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['work_line', 'starts_at', 'ends_at'], name='appointment_line_time_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'status'], name='appt_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['manual_channel'], name='appointment_channel_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='appointment_starts_before_ends'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_minutes__gt', 0)), name='appointment_duration_positive'),
        ),
    ]
