# Generated by Django 5.2.15 on 2026-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='manual_channel',
            field=models.CharField(choices=[('telefono', 'Telefono'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('mostrador', 'Mostrador'), ('web_publica', 'Web publica'), ('otro', 'Otro')], default='telefono', max_length=20, verbose_name='canal de origen'),
        ),
    ]
