# Generated by Django 5.2.15 on 2026-07-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_appointment_no_show_outcome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesscalendarsettings",
            options={
                "verbose_name": "configuración de calendario",
                "verbose_name_plural": "configuraciones de calendario",
            },
        ),
        migrations.AlterModelOptions(
            name="workline",
            options={
                "ordering": ["business__commercial_name", "display_order", "line_number"],
                "verbose_name": "línea de trabajo",
                "verbose_name_plural": "líneas de trabajo",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="motivo de cancelación",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="fecha de cancelación",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="duration_adjustment_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="motivo de ajuste de duración",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="manual_channel",
            field=models.CharField(
                choices=[
                    ("telefono", "Teléfono"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("mostrador", "Mostrador"),
                    ("web_publica", "Reserva online"),
                    ("otro", "Otro"),
                ],
                default="telefono",
                max_length=20,
                verbose_name="canal de origen",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="total_duration_minutes",
            field=models.PositiveIntegerField(verbose_name="duración total"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="work_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="booking.workline",
                verbose_name="línea de trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentservice",
            name="duration_minutes_snapshot",
            field=models.PositiveIntegerField(verbose_name="duración snapshot"),
        ),
        migrations.AlterField(
            model_name="availabilityrule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                verbose_name="día de semana",
            ),
        ),
        migrations.AlterField(
            model_name="businessclosure",
            name="closure_type",
            field=models.CharField(
                choices=[
                    ("vacaciones", "Vacaciones"),
                    ("festivo_local", "Festivo local"),
                    ("festivo_autonomico_manual", "Festivo autonómico manual"),
                    ("bloqueo_puntual", "Bloqueo puntual"),
                    ("cierre_negocio", "Cierre de negocio"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=40,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="businessclosure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="businessclosure",
            name="work_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closures",
                to="booking.workline",
                verbose_name="línea de trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(verbose_name="duración en minutos"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="última actualización"),
        ),
        migrations.AlterField(
            model_name="workline",
            name="line_number",
            field=models.PositiveSmallIntegerField(verbose_name="número de línea"),
        ),
    ]
