# Generated by Django 5.2.16 on 2026-07-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_businesscalendarsettings_options_and_more'),
        ('customers', '0005_businessclientaccessgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested_by_client_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_appointments', to='customers.businessclientaccess', verbose_name='cuenta que solicitó la cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_by_name_snapshot',
            field=models.CharField(blank=True, max_length=160, verbose_name='nombre de quien solicitó la cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_by_relationship_snapshot',
            field=models.CharField(blank=True, max_length=80, verbose_name='relación de quien solicitó la cita'),
        ),
    ]
