# Generated by Django 5.2.16 on 2026-07-16 15:25

from django.db import migrations, models


def normalize_closed_appointment_timestamps(apps, schema_editor):
    appointment = apps.get_model("booking", "Appointment")
    appointment.objects.filter(
        models.Q(completed_at__isnull=True)
        | models.Q(completed_at__lt=models.F("ends_at")),
        status="completada",
    ).update(completed_at=models.F("ends_at"))
    appointment.objects.filter(
        models.Q(no_show_marked_at__isnull=True)
        | models.Q(no_show_marked_at__lt=models.F("ends_at")),
        status="no_presentada",
    ).update(no_show_marked_at=models.F("ends_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_appointment_requested_by_client_access_and_more"),
    ]

    operations = [
        migrations.RunPython(
            normalize_closed_appointment_timestamps,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status="completada")
                    | models.Q(
                        completed_at__isnull=False,
                        completed_at__gte=models.F("ends_at"),
                    )
                ),
                name="appt_completed_at_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status="no_presentada")
                    | models.Q(
                        no_show_marked_at__isnull=False,
                        no_show_marked_at__gte=models.F("ends_at"),
                    )
                ),
                name="appt_no_show_at_valid",
            ),
        ),
    ]
