# Generated by Django 5.2.16 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_enforce_appointment_outcomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="public_confirmation_reference",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text=(
                    "Identificador idempotente del borrador público. "
                    "Las citas creadas por profesionales no lo utilizan."
                ),
                null=True,
                unique=True,
                verbose_name="referencia de confirmación pública",
            ),
        ),
    ]
