# Generated by Django 5.2.15 on 2026-06-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('internal', 'Interna')], max_length=20, verbose_name='canal')),
                ('event_type', models.CharField(choices=[('appointment_confirmed', 'Cita confirmada'), ('appointment_cancelled', 'Cita cancelada'), ('internal_reminder', 'Recordatorio interno')], max_length=40, verbose_name='evento')),
                ('content', models.TextField(verbose_name='contenido')),
                ('status', models.CharField(choices=[('registrada', 'Registrada'), ('simulada', 'Simulada'), ('leida', 'Leida'), ('descartada', 'Descartada')], default='registrada', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.appointment', verbose_name='cita')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business', verbose_name='negocio')),
                ('business_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.businessclient', verbose_name='ficha de cliente')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario destinatario')),
            ],
            options={
                'verbose_name': 'notificacion interna',
                'verbose_name_plural': 'notificaciones internas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='notif_business_status_idx'), models.Index(fields=['event_type'], name='notification_event_idx')],
            },
        ),
    ]
