# Generated by Django 5.2.16 on 2026-07-14 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_requested_by_client_access_and_more'),
        ('businesses', '0011_businesssignuprequest'),
        ('customers', '0009_businessclientaccess_email_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('professional_activation', 'Activación profesional'), ('professional_email_verification', 'Verificación profesional'), ('client_email_verification', 'Verificación cliente'), ('appointment_confirmation', 'Confirmación de cita'), ('appointment_reminder', 'Recordatorio de cita')], max_length=48, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=16, verbose_name='estado')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('deduplication_key', models.CharField(max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='programado para')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='último error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='booking.appointment')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='businesses.business')),
                ('client_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='customers.businessclientaccess')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', 'pk'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='email_status_schedule_idx')],
            },
        ),
    ]
