# Generated by Django 5.2.16 on 2026-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_outboundemail_delivery_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='contenido operativo'),
        ),
        migrations.AlterField(
            model_name='outboundemail',
            name='kind',
            field=models.CharField(choices=[('professional_activation', 'Activación profesional'), ('professional_email_verification', 'Verificación profesional'), ('client_email_verification', 'Verificación cliente'), ('client_password_reset', 'Recuperación de contraseña cliente'), ('appointment_confirmation', 'Confirmación de cita'), ('appointment_reminder', 'Recordatorio de cita'), ('operational_notice', 'Aviso operativo')], max_length=48, verbose_name='tipo'),
        ),
    ]
