# Generated by Django 5.2.16 on 2026-07-23 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_outboundemail_payload_alter_outboundemail_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboundemail",
            options={
                "ordering": ["scheduled_for", "pk"],
                "verbose_name": "correo transaccional",
                "verbose_name_plural": "correos transaccionales",
            },
        ),
    ]
